### ISSUE TITLE
Car play won't start

### ISSUE THREAD

**Issue by raresmihaila** [hansemannn/iOS12-CarPlay-Example#1]
The app runs and the map is displayed but nothing is shown on the car play simulator when I start it. Are there any additional steps needed?

Also the app won't stop at breakpoint in 

func application(_ application: UIApplication, didConnectCarInterfaceController interfaceController: CPInterfaceController, to window: CPMapContentWindow)

If I put a breakpoint there.

![screen shot 2018-07-02 at 14 38 59](https://user-images.githubusercontent.com/40762163/42162014-d228732e-7e05-11e8-8de1-e55b2f2e8afb.png)

**Comment by bradtheappguy** [comment]
same here.  I spent a few hours over the weekend trying to get this top work with the same results.  I tested on both High Sierra + Xcode Beta2 and Mojave + Xcode Beta2.   Do we need a special entry in an entitlements file or something?

**Comment by hansemannn** [comment]
You need to apply for CarPlay based entitlements before being able to connect. 

Quote from Apple:
> The referenced project does not have the necessary entitlement to appear on the car screen. Please visit https://developer.apple.com/carplay/ to apply for the navigation app entitlement.

**Comment by OzBob** [comment]
No you don't have to apply for entitlement when only debugging.

https://blog.flitsmeister.nl/start-developing-your-navigation-app-for-carplay-6e4c6c2b4e47

Create a file: Route66.entitlements

With Content: 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.carplay-maps</key>
	<true/>
</dict>
</plist>

as per; https://github.com/Svantulden/carplay-navigation/blob/master/CarplayNavigationTesting/CarplayNavigationTesting.entitlements

**Comment by hansemannn** [comment]
@OzBob Great feedback! Can you do a PR to add this?

**Comment by hansemannn** [comment]
Fixed in a recent commit. There is still an open issue where the map view does not appear, but that's unrelated to the actual car-connection that now works.

**Comment by OzBob** [comment]
I'll do a PR once I can get the project building and debugging... getting some error about Bundle Identifier, but when I change it and the team, I then start getting 'Automatic singing can't add' the entitlements. " Switch to manual signing and resolve the issue by downloading a matching provisioning profile from the developer website. Alternatively, to continue using automatic signing, remove these entitlements from your entitlements file and their associated functionality from your code."
