### ISSUE TITLE
undeclared type 'CPMapTemplateConfiguration'

### ISSUE THREAD

**Issue by OzBob** [hansemannn/iOS12-CarPlay-Example#2]
Install Xcode 10.0 beta 4
Clone
Build

hansemannn/iOS12-CarPlay-Example/Route66/RootMapTemplate.swift:14:32: Use of undeclared type 'CPMapTemplateConfiguration'

hansemannn/iOS12-CarPlay-Example/Route66/AppDelegate.swift:22:138: Use of undeclared type 'CPMapContentWindow'

**Comment by hansemannn** [comment]
This class only works on device, there is an open radar for that.

**Comment by OzBob** [comment]
Do you have a link to the radar so i can monitor it?

**Comment by hansemannn** [comment]
Actually, it was a class that was replaced recently. I just pushed my latest changes!

**Comment by hansemannn** [comment]
There still seem to be an issue where CarPlay connects, but the map is not shown. I only played with it a bit so far, so input is very welcome!
