### ISSUE TITLE
Bundle Identifier

### ISSUE THREAD

**Issue by OzBob** [hansemannn/iOS12-CarPlay-Example#3]
Sorry if this is a newbie questions.

I am getting some error about Bundle Identifier, but when I change from yours to mine and change the team from yours to mine, I then start getting 'Automatic singing can't add' the entitlements. " Switch to manual signing and resolve the issue by downloading a matching provisioning profile from the developer website. Alternatively, to continue using automatic signing, remove these entitlements from your entitlements file and their associated functionality from your code."

Can you suggest anything to help?

**Comment by JeffSchroeder** [comment]
I just pull xCode 10 beta 4, so to get this to run locally:
1) Update bundle to com.you.Route66
2) Auto sign to your profile
3) Remove reference the entitlements file 
4) In target / build settings / signing   remove the the entitlements there too.
That got it to work for me.  Doesn't seem to need the entitlement for dev anymore.

**Comment by OzBob** [comment]
Build. Run. Enter location. All OK.
Now I will begin the journey of joining the Apple CarPlay programming to get the CarPlay simulator etc.
